### ISSUE TITLE
Extract data from PLLs

### ISSUE THREAD

**Issue by jaliasd** [ICPI/COP19#1]
PLL - MSD Comparison Analysis
--
Following a leads meeting there was a request to support a short analytic project comparing the planning level letters to the MSD. The desire is to have a table that people can use as a reference as they get questions from their country teams about the consistency of the values in the letters. We may also use it internally to prioritize areas of support per OU.

Draft steps (these may change)
1.	Extract the data from PLL into excel (~2 hours?)
2.	Compare the data in the PLL table to MSD (~2 hours)
3.	Create summary table/slide  (30 mins)
4.	Save on SP and send to leads (5 mins)

Activity Summary
--
There several data point in the COP19 PLLs that are not collated in one place. This activity will harvest those data.

Using the template [ here ](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/COP%20Support/COP%2019/PLL%20-%20MSD%20Analysis) complete the two tabs in green (see Shazad for in person instructions). Check off the countries as you complete them. And post your completed template back to the above link

Fiscal Years to Include for MER and Outlays
--
FY19 Targets (Table 7 - COP18 FY19)
FY 20 Targets  (Table 7 - COP19 FY20) 
COP 17 - FY18 Budget is Included (Outlays)

| Josh | Nicole | Mala | Faith|
|---------|-----| --------|------|
|<ul><li>[x] Angola</li><li> [x] Asia Regional</li><li> - [x] Botswana</li><li>- [x] Burundi</li><li>- [x] Cameroon | <ul><li>- [x] Côte d’Ivoire </li><li> - [x] DRC </li><li>- [x] Ethiopia </li><li>- [x] eSwatini </li><li> - [x] Haiti </li><li>- [x] Kenya| <ul><li> - [x] Lesotho </li><li> - [x] Malawi </li><li> - [x] Mozambique </li><li>- [x] Namibia </li><li> - [x] Nigeria </li><li> - [x] PNG </li><li> - [x] Rwanda | <ul><li> - [x] South Africa </li><li>- [x] South Sudan </li><li> - [x] Tanzania </li><li> - [x] Uganda </li><li>- [x] Ukraine </li><li>- [x] Vietnam </li><li> - [x] Zambia</li><li> - [x] Zimbabwe

Next Steps
--

- [x] Merge extracted data (Josh)
- [x] Merge PLL and MSD
- [x] QC
- [x] Finalize Analysis (Faith & Jasmine)
- [x] Distribute (Jasmine) - Sent to leads 2/12

### SharePoint Folder [Here ](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP%2019%2FPLL%20%2D%20MSD%20Analysis&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

**Comment by jb3436** [comment]
I am closing the original coordination issue on the PLL and will track the progress here. 
https://github.com/ICPI/Coordination/issues/46

**Comment by vanamala-narasimhan** [comment]
Section for Mala complete and spreadsheet uploaded to sharepoint

**Comment by achafetz** [comment]
here's the code to pull from the "definitive" sources for budget and MER.

https://github.com/ICPI/COP19/blob/master/extract_budget_mer.R

Data is posted to the [same folder](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2fOGAC-HQ%2ficpi%2fShared%20Documents%2fCOP%20Support%2fCOP%2019%2fPLL%20-%20MSD%20Analysis&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691) as the templates.

**Comment by jb3436** [comment]
Final Analysis 
--
Saved on SharePoint in [ COP19 Support Folder ](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/COP%20Support/COP%2019/PLL%20-%20MSD%20Analysis)

**Comment by jaliasd** [comment]
File uploaded. Not sure what the follow on here is? @jb3436 ?

**Comment by jb3436** [comment]
Next Steps
--

- [x] Extract the data from PLL into excel (~2 hours?) (Faith, Mala, Nicole)
- [x] Compare the data in the PLL table to MSD (~2 hours) (@faithfawale & @jb3436 ) (Due 1/29)
- [x] Create summary table/slide (30 mins) (@faith @jb3436 )
- [x] Save on SP and send to leads (5 mins) (@faithfawale @jb3436  )

**Comment by jb3436** [comment]
Methods Summary
--

- Data entered into template
- Template merged into dataset
- MSD pivots set up & QC'd against pano and DATIM
- Set up MSD so that the disaggregates for the 4 indicators were aligned with the disaggregates in the PLL
- Gathered changed the wide time period from MSD to Long
- Concactanated the Age/Sex columns
- Merged PLL and MSD
- Created a table for review by OU by indicator and age/sex disagg with highlighted difference

**Note**: <15 needs to combine (<15M, <15F & <15 unknown to match <15 in PLL)

In FY18 Values (not included in this analysis) several issues were found in the PLL. 

**Status Update:**
- Need to specify period extracted from PLLs. 
- Currently it says 2018 and 2019. I assumed this referred to FY, but it seems to refer to COP year. 
- The period should be FY period and should cover FY18-20. Currently the period is COP 18-19 (FY19-20).

**Comment by jaliasd** [comment]
@faithfawale @shazadahmed10 

You should subset and aggregate the OU x IM MSD to the OU, this comparison file is 122 mb. Also, delete extraneous cols from the MSD.

Also, clean up the 'comparison table', freeze top row, check spelling errors, etc.. Consider user experience; I can't tell what I am looking at here or where there are discrepancies. Consider a 'face sheet' that simply tells me which countries for which indicators there is a difference between the PPL and DATIM.

**Comment by jb3436** [comment]
@jaliasd @shazadahmed10 I am going to take a stab at formatting the table into a final product. 

FYI - @faithfawale

**Comment by jb3436** [comment]
## Status:

- Completed 
- Final table sent out to leads for review 2/12
- Summary included

@faithfawale @jaliasd @shazadahmed10

**Comment by jb3436** [comment]
Observations
--
![image](https://user-images.githubusercontent.com/13006198/52599576-07255480-2e27-11e9-811b-18de6339c1f8.png)

**Comment by jb3436** [comment]
Snapshot from Cover Page (No data included)
--
![image](https://user-images.githubusercontent.com/13006198/52655566-6dab8080-2ec2-11e9-9381-b0a9f2df3369.png)
![image](https://user-images.githubusercontent.com/13006198/52655606-85830480-2ec2-11e9-97a0-0f6baee08d29.png)

**Comment by jb3436** [comment]
QC Conducted - no issues found
Sent to Leads for distribution

**Comment by jb3436** [comment]
Final Analysis on SharePoint

[ICPI > COP Support > COP 19 > PLL Analysis ](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP%2019%2FPLL%20%2D%20MSD%20Analysis&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence)
