### ISSUE TITLE
Botswana Unmet Need Analysis Request 

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP19#16]
Request to support HTS analysis on unment need based off of NIgeria's example  using Spectrum data. 
Email: COP HTS Slides

Response: 
The treatment cluster has highlighted that you can get the values for the analysis from the TSD.  Connected Tola with Michelle and Katie. 

For on site support:  
Since this request is for SPECTRUM, I suggest asking Shabeen Ally (who is on site) to connect you with the SPECTRUM team who is also on site to provide support.

**Comment by shapaklyak** [comment]
@jb3436 also sent the links to the TSD to Kristin Roha who is PPM yesterday.

On a second note, looked at TSD and there is no standardization across tabs - missing titles, slicers in different places within the tool, some of the visualizations can be more easily consolidated.

**Comment by jb3436** [comment]
@shapaklyak Thanks! Could you take a look after COP and do a layout review?
