### ISSUE TITLE
Cote d'Ivoire Agency COP Support TDY

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP19#3]
Please describe lessons learned here

**Comment by imujawar** [comment]
### Objective: Continued work on the Agent Based Model (ABM)* simulating presumed patient movement between PEPFAR supported sites to understand where patients are seeking treatment after being tested positive.

- [x] Analysis of patient movement across facilities using facility testing and treatment numbers 
- [x] Proportional distribution of patients in a facility to other facilities 
- [ ] Adapting linkage model to retention for silent transfers and loss
- [x] Preliminary COP support in preparation of subsequent week TDY
- [ ] Adjusted ART coverage (and gap) at district level based on surrounding patient flux probabilities

Slides posted on [SharePoint](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FCOP%20Support%2FCOP%2019%2FCDI%20agent%2Dbased%2Dmodel%20TDY&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D).  

*ABM developed by Ray Shiraishi and Roma Bhatkoti (SEM/HIDMSB/CDC).

**Comment by imujawar** [comment]
No follow-up related to COP.
