### ISSUE TITLE
Eswatini COP Support

### ISSUE THREAD

**Issue by jb3436** [ICPI/COP19#4]
Please describe COP support that others may learn from

**Comment by erinschelar** [comment]
-Developed prevention targets using COP guidance and historical program data for KP, PP, PrEP, and OVC in the datapack and worked with activity managers to distribute IM targets
-Reviewed DRT with SI team using Q1 data submission and provided training materials for reference to assist with data cleaning and review process
-Troubleshooting of COP tool alignment 
-Agency specific partner management support
